;(global-set-key (kbd "<f9>") 'find-tag-other-window)
;(global-set-key (kbd "<f8>") 'find-tag)
;(global-set-key (kbd "<f5>") (kbd "C-u <f8>"))
;(global-set-key (kbd "C-:") 'tags-search)
;(global-set-key (kbd "<f6>") 'tags-loop-continue)
;(global-set-key (kbd "C-,") 'ctl-x-4-prefix)
;(global-set-key (kbd "C-;") 'ctl-x-5-prefix)
;(global-set-key (kbd "<f7>") 'compile)
;(global-set-key (kbd "C-&") (kbd "C-x r s 1"))
;(global-set-key (kbd "C-é") (kbd "C-x r i 1 C-e"))
;(global-set-key (kbd "C-\"") (kbd "C-x r r 2"))
;(global-set-key (kbd "C-'") (kbd "C-x r i 2 C-e"))
;(global-set-key (kbd "C-(") (kbd "C-x h C-S-c"))
;(global-set-key (kbd "C--") (kbd "C-x h C-S-v"))
;(global-set-key (kbd "<C-tab>") (kbd "C-x `"))
;(global-set-key (kbd "M-RET") (kbd "M-<left> M-S-<right>"))
;(global-set-key (kbd "M-S-<up>") (kbd "C-<SPC> C-<up>"))
;(global-set-key (kbd "M-S-<down>") (kbd "C-<SPC> C-<down>"))
;(global-set-key (kbd "M-<up>") (kbd "C-<up>"))
;(global-set-key (kbd "M-<down>") (kbd "C-<down>"))
;(global-unset-key (kbd "C-z"))
;(global-unset-key (kbd "C-x z"))
;(global-unset-key (kbd "C-x C-z"))

(global-set-key [(f3)] 'string-rectangle)
(global-set-key [(f4)] 'rm-kill-region)
;(global-set-key [(f5)] 'yank-rectangle)
;(global-set-key [(f6)] 'rm-kill-ring-save)
;(global-set-key (kbd "<f4>") 'find-tag-other-window)
;(global-set-key (kbd "<f5>") 'find-tag)
(global-set-key (kbd "<f9>") 'find-tag-other-window)
(global-set-key (kbd "<f8>") 'find-tag)
(global-set-key (kbd "<f5>") (kbd "C-u <f8>"))
(global-set-key (kbd "C-:") 'tags-search)
(global-set-key (kbd "<f6>") 'tags-loop-continue)

;(global-set-key (kbd "<f6>") (kbd "C-u <f8>"))
;(global-set-key (kbd "C-:") 'tags-search)
(global-set-key (kbd "C-c g")   'list-matching-lines)

(global-set-key [end] 'end-of-buffer)
(global-set-key [home] 'beginning-of-buffer)
(global-set-key [S-end] 'end-of-line)
(global-set-key [S-home] 'beginning-of-line)
(global-set-key [C-end] 'end-of-line)
(global-set-key [C-home] 'beginning-of-line)

;; replace 'lost' font menu
(define-key global-map [S-down-mouse-3] 'mouse-set-font)

;; customized leybindings
;(global-set-key [(f7)] 'compile)
;(global-set-key [(f8)] 'recompile)
(global-set-key [(f1)] 'indent-region)
(global-set-key [(f2)] 'speedbar-get-focus)
(global-set-key [(f10)] 'goto-line)
(global-set-key [(f11)] 'c++-mode)
(global-set-key [(f12)] 'font-lock-fontify-buffer)

(global-set-key [C-up] 'shrink-window)
(global-set-key [C-down] 'enlarge-window)
(global-set-key [C-left] 'shrink-window-horizontally)
(global-set-key [C-right] 'enlarge-window-horizontally)

;(global-set-key [mouse-4] 'previous-line)
;(global-set-key [mouse-5] 'forward-line)
(global-set-key [S-left] 'backward-word)
(global-set-key [S-right] 'forward-word)

(autoload 'octave-mode "octave-mod" nil t)
(setq auto-mode-alist
(cons '("\\.m$" . octave-mode) auto-mode-alist))
(add-hook 'octave-mode-hook
(lambda ()
(abbrev-mode 1)
(auto-fill-mode 1)
(if (eq window-system 'x)
(font-lock-mode 1))))

